----- Begin Fatal Exception 03-Dec-2021 14:17:27 CET-----------------------
An exception of category 'ConfigFileReadError' occurred while
   [0] Processing the python configuration file named produceLHEGEN39.0.py
Exception Message:
 unknown python problem occurred.
AttributeError: 'Process' object has no attribute 'generator'

At:
  produceLHEGEN39.0.py(89): <module>

----- End Fatal Exception -------------------------------------------------
